### ISSUE TITLE
Auto Cut

### ISSUE THREAD

**Issue by foxbloodiron** [marcusfelix/esc-pos-printer-flutter#9]
hello sir,  i would like to know is there any code for auto cut print?

**Comment by marcusfelix** [comment]
Try sending '\x1d\x56\x00'

**Comment by foxbloodiron** [comment]
it worked sir, thank you

**Comment by mangaldaslima3117** [comment]
Hello,
I am using pdf package to generate a pdf which I am printing through print dialog, I have 3 section in that generated bill. How can I send this command mentioned on the answer "\x1d\x56\x00", so that each section can be autocut, any suggestion would be very helpful.

Code below.
final pdfWidgets.Document doc = pdfWidgets.Document();

    // Build your bill content
    // Replace the following code with your actual bill sections and content
    doc.addPage(
      pdfWidgets.Page(
        build: (context) {
          return pdfWidgets.Center(
            child: pdfWidgets.Text('Bill Section 1'),
          );
        },
      ),
    );

    doc.addPage(
      pdfWidgets.Page(
        build: (context) {
          return pdfWidgets.Center(
            child: pdfWidgets.Text('Bill Section 2'),
          );
        },
      ),
    );

    doc.addPage(
      pdfWidgets.Page(
        build: (context) {
          return pdfWidgets.Center(
            child: pdfWidgets.Text('Bill Section 3'),
          );
        },
      ),
    );

    // Generate PDF data
    final pdfData = await doc.save();

    // Print the PDF using the printing package
    await Printing.layoutPdf(
      onLayout: (format) => pdfData.bytes,
    );

  }
